In [ ]:
Phase 2: Array Operations(ufuncus)

Task (Grace units): The manager decides to add **2 "bonus" units** to every products daily sale for a holiday report. add  2 to the entire daily_sales array. task2.2 (Revenue): Calculate the total revenue for each day.

Multiply the cost_price array by the daily_sales matrix.
Observe how numpy handles the multiplication of  1d and 2 array.

Task2.3 (Scaling): Use np.sqrt() on the sales data to find the square root of all sales values for statistical curve.

In [1]:
import numpy as np

# daily sales of 3 products over 5 days
daily_sales = np.array([
    [10, 12, 8, 9, 11],
    [5, 7, 6, 8, 7],
    [20, 18, 22, 19, 21]
])

# cost price of each product
cost_price = np.array([100, 60, 150])


In [2]:
daily_sales_bonus = daily_sales + 2
print(daily_sales_bonus)

[[12 14 10 11 13]
 [ 7  9  8 10  9]
 [22 20 24 21 23]]


In [3]:
revenue = daily_sales_bonus * cost_price[:, np.newaxis]
print(revenue)


[[1200 1400 1000 1100 1300]
 [ 420  540  480  600  540]
 [3300 3000 3600 3150 3450]]


In [4]:
total_revenue_per_day = revenue.sum(axis=0)
print(total_revenue_per_day)


[4920 4940 5080 4850 5290]


In [5]:
sqrt_sales = np.sqrt(daily_sales_bonus)
print(sqrt_sales)


[[3.46410162 3.74165739 3.16227766 3.31662479 3.60555128]
 [2.64575131 3.         2.82842712 3.16227766 3.        ]
 [4.69041576 4.47213595 4.89897949 4.58257569 4.79583152]]


Phase 3: Slicing and Indexing 

Task3.1: Access the sales data for smartwatches (Row 1) for all 4 days.
Task 3.2: Access the sales data for all products for the first two days (monday and tuesday) task 3.3 Access the sale of speakers on Thursday specifically using double indexing. Task 3.4: Using slicing, extract a 2 8 2 sub array representing the sales of headphones and smartwatches for monday and tuesday.

In [6]:

import numpy as np

# Rows → Products
# Columns → Days (Mon, Tue, Wed, Thu)

daily_sales = np.array([
    [10, 12, 8, 9],    # Headphones (Row 0)
    [5, 7, 6, 8],      # Smartwatches (Row 1)
    [20, 18, 22, 19]   # Speakers (Row 2)
])


In [7]:
smartwatch_sales = daily_sales[1, :]
print(smartwatch_sales)


[5 7 6 8]


In [8]:
first_two_days = daily_sales[:, 0:2]
print(first_two_days)


[[10 12]
 [ 5  7]
 [20 18]]


In [9]:
speaker_thursday = daily_sales[2][3]
print(speaker_thursday)


19


In [10]:
sub_array = daily_sales[0:2, 0:2]
print(sub_array)


[[10 12]
 [ 5  7]]


Phase 4: Reshaping and Linspace 

Task 4.1: Flatten the 3 * 4 daily_sales array into a 1d array of 12 elements using  .reshape(). Task 4.2: Convert the sales data into a 2 * 6 matrix. task 4.3: use np.linspace to create an array of 10 equal intervals between 0 and 100  to represent "Discount Percenatges".

In [11]:
import numpy as np

daily_sales = np.array([
    [10, 12, 8, 9],
    [5, 7, 6, 8],
    [20, 18, 22, 19]
])


Phase 5: The Random Module 

Task 5.1: Use np.random.randint to generate a new 3 * 4 array of "Predicted Sales" for the next week with the values of ranging from 0 to 20. Task 5.2: Generate a random array of 5 numbers between 0 and 1 using np.random.rand . task 5.3: Use np.sum() to find: 
Total items sold over all 4 days.
Total items sold for each product ( sum across rows).

# Axis in NumPy

In [13]:
import numpy as np
arr = np.array([[1,2,3],
[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
print(np.sum(arr))

21


In [ ]:
print(np.sum(arr, axis = 0)) #column

[5 7 9]


In [ ]:
print(np.sum(arr, axis = 1))#row

[ 6 15]


# Where in Numpy

In [18]:
arr = np.array([10, -5, 20, -3, 15])
result = np.where(arr < 0, 0, arr)
print(result)

[10  0 20  0 15]


In [19]:
arr = np.where(arr % 2!=0, -1, arr)
print(result)

[10  0 20  0 15]


In [20]:
marks= np.array([45, 78, 32, 90, 55])
status = np.where(marks>=50,1,0)

print(status)

[0 1 0 1 1]


In [22]:
data=np.array([10,20,30,40,50])
mean_val = np.mean(data)
result=np.where(data>mean_val, mean_val,data)

# Applying (Where)condition in 2d array

In [23]:
mat = np.array([
    [10,60,30],
    [80,20,90]
])
result  = np.where(mat>=50, 1,0)
print(result)

[[0 1 0]
 [1 0 1]]
